// Generated by oh_proto; do not edit.
export const PROTOCOL_VERSION = "m0-v1" as const;
export type TimeCommand = { "type": "Pause", paused: boolean, } | { "type": "SetSpeed", speed: number, };
export type PackInfo = { id: string, version: string, hash: string, };
export type TimeState = {
/**
 * Fully formatted by the server; browsers never calculate dates.
 */
date: string, hour: number,
/**
 * Decimal text preserves full u64 precision in JavaScript.
 */
tick: string, paused: boolean, speed: number, };
export type ClientMessage = { "type": "Hello", protocol_version: string, } | { "type": "Create", scenario: string, seed: string, mode: string, } | { "type": "Join", session: string, nation: string | null, } | { "type": "Command", sequence: string, command: TimeCommand, } | { "type": "Query", request: string, kind: string, };
export type ServerMessage = { "type": "Welcome", engine_version: string, protocol_version: string, accepted: boolean, reason_key: string | null, packs: Array<PackInfo>, sessions: Array<string>, } | { "type": "CommandResult", sequence: string, accepted: boolean, reason_key: string | null, } | { "type": "Snapshot", state: TimeState, } | { "type": "Delta", sequence: string, state: TimeState, } | { "type": "QueryResult", request: string, supported: boolean, reason_key: string | null, state: TimeState | null, } | { "type": "Notice", key: string, };
