// Generated by oh_proto; do not edit.
export const PROTOCOL_VERSION = "m0-v1" as const;
export const MAP_DISPLAY_VERSION = 1 as const;
export type TimeCommand = { "type": "Pause", paused: boolean, } | { "type": "SetSpeed", speed: number, };
export type PackInfo = { id: string, version: string, hash: string, };
export type TimeState = {
/**
 * Fully formatted by the server; browsers never calculate dates.
 */
date: string, hour: number,
/**
 * Decimal text preserves full u64 precision in JavaScript.
 */
tick: string, paused: boolean, speed: number, };
export type NationFlagsView = { nation: number, keys: Array<string>, };
export type EndCauseView = { "type": "Date" } | { "type": "Condition" } | { "type": "Explicit", source: string, };
export type EndView = { tick: string, date: string, hour: number, causes: Array<EndCauseView>, };
export type TriggerView = { definitions_hash: string, flags: Array<NationFlagsView>, ended: EndView | null, };
export type LedgerRow = { id: string, label_key: string, operation_key: string, value: string, accumulated: string, source_key: string | null, };
export type LedgerView = { base: string, final_value: string, tick: string, entries: Array<LedgerRow>, };
export type SupportView = { name_key: string, value: string, };
export type NationView = { id: number, tag: string, name_key: string, color: [number, number, number], capital: number, government_key: string, support: Array<SupportView>, };
export type ScalarView = { name_key: string, value: string, };
export type StateView = { id: number, name_key: string, provinces: Array<number>, owner: number, population: string, resources: Array<ScalarView>, buildings: Array<ScalarView>, infrastructure: LedgerView, };
export type ProvinceView = { id: number, state: number | null, owner: number | null, controller: number | null, owner_color: [number, number, number] | null, controller_color: [number, number, number] | null, terrain_key: string, terrain_color: [number, number, number], state_color: [number, number, number] | null, };
export type WorldView = { tick: string, map_id: string, width: number, height: number, province_ids: Array<number>, neutral_color: [number, number, number], mode_keys: Array<string>, nations: Array<NationView>, states: Array<StateView>, provinces: Array<ProvinceView>, };
export type MapStyle = { background: [number, number, number], nation_border: [number, number, number], state_border: [number, number, number], province_border: [number, number, number], selected: [number, number, number], hovered: [number, number, number], nation_width_milli: number, state_width_milli: number, province_width_milli: number, highlight_milli: number, fit_milli: number, zoom_min_milli: number, zoom_max_milli: number, wheel_milli: number, drag_threshold: number, };
export type MapMetadata = { schema_version: number, map_id: string, width: number, height: number, province_ids: Array<number>, pack_hash: string, index_hash: string, byte_length: string, style: MapStyle, };
export type ClientMessage = { "type": "Hello", protocol_version: string, } | { "type": "Create", scenario: string, seed: string, mode: string, } | { "type": "Join", session: string, nation: string | null, } | { "type": "Command", sequence: string, command: TimeCommand, } | { "type": "Query", request: string, kind: string, };
export type ServerMessage = { "type": "TriggerResult", request: string, supported: boolean, reason_key: string | null, trigger: TriggerView | null, } | { "type": "Welcome", engine_version: string, protocol_version: string, accepted: boolean, reason_key: string | null, packs: Array<PackInfo>, sessions: Array<string>, } | { "type": "CommandResult", sequence: string, accepted: boolean, reason_key: string | null, } | { "type": "Snapshot", state: TimeState, } | { "type": "Delta", sequence: string, state: TimeState, } | { "type": "QueryResult", request: string, supported: boolean, reason_key: string | null, state: TimeState | null, } | { "type": "WorldResult", request: string, supported: boolean, reason_key: string | null, world: WorldView | null, } | { "type": "Notice", key: string, };
