// Generated by oh_proto; do not edit.
export const PROTOCOL_VERSION = "m0-v1" as const;
export const MAP_DISPLAY_VERSION = 1 as const;
export type TimeCommand = { "type": "Pause", paused: boolean, } | { "type": "SetSpeed", speed: number, };
export type PackInfo = { id: string, version: string, hash: string, };
export type TimeState = {
/**
 * Fully formatted by the server; browsers never calculate dates.
 */
date: string, hour: number,
/**
 * Decimal text preserves full u64 precision in JavaScript.
 */
tick: string, paused: boolean, speed: number, };
export type NationFlagsView = { nation: number, keys: Array<string>, };
export type EndCauseView = { "type": "Date" } | { "type": "Condition" } | { "type": "Explicit", source: string, };
export type EndView = { tick: string, date: string, hour: number, causes: Array<EndCauseView>, };
export type TriggerView = { definitions_hash: string, flags: Array<NationFlagsView>, ended: EndView | null, };
export type LedgerRow = { id: string, label_key: string, operation_key: string, value: string, accumulated: string, source_key: string | null, };
export type LedgerView = { base: string, final_value: string, tick: string, entries: Array<LedgerRow>, };
export type SupportView = { name_key: string, value: string, };
export type NationView = { id: number, tag: string, name_key: string, color: [number, number, number], capital: number, government_key: string, support: Array<SupportView>, };
export type ScalarView = { name_key: string, value: string, };
export type StateView = { id: number, name_key: string, provinces: Array<number>, owner: number, population: string, resources: Array<ScalarView>, buildings: Array<ScalarView>, infrastructure: LedgerView, };
export type ProvinceView = { id: number, state: number | null, owner: number | null, controller: number | null, owner_color: [number, number, number] | null, controller_color: [number, number, number] | null, terrain_key: string, terrain_color: [number, number, number], state_color: [number, number, number] | null, };
export type WorldView = { tick: string, map_id: string, width: number, height: number, province_ids: Array<number>, neutral_color: [number, number, number], mode_keys: Array<string>, nations: Array<NationView>, states: Array<StateView>, provinces: Array<ProvinceView>, };
export type MapStyle = { background: [number, number, number], nation_border: [number, number, number], state_border: [number, number, number], province_border: [number, number, number], selected: [number, number, number], hovered: [number, number, number], nation_width_milli: number, state_width_milli: number, province_width_milli: number, highlight_milli: number, fit_milli: number, zoom_min_milli: number, zoom_max_milli: number, wheel_milli: number, drag_threshold: number, };
export type MapMetadata = { schema_version: number, map_id: string, width: number, height: number, province_ids: Array<number>, pack_hash: string, index_hash: string, byte_length: string, style: MapStyle, };
export type ClientMessage = { "type": "Hello", protocol_version: string, } | { "type": "Create", scenario: string, seed: string, mode: string, } | { "type": "Join", session: string, nation: string | null, } | { "type": "Command", sequence: string, command: TimeCommand, } | { "type": "Query", request: string, kind: string, } | { "type": "MilitaryCommand", sequence: string, command: MilitaryCommand, } | { "type": "ProductionCommand", sequence: string, command: ProductionCommand, } | { "type": "EconomyCommand", sequence: string, command: EconomyCommand, };
export type ServerMessage = { "type": "TriggerResult", request: string, supported: boolean, reason_key: string | null, trigger: TriggerView | null, } | { "type": "Welcome", engine_version: string, protocol_version: string, accepted: boolean, reason_key: string | null, packs: Array<PackInfo>, sessions: Array<string>, } | { "type": "CommandResult", sequence: string, accepted: boolean, reason_key: string | null, } | { "type": "Snapshot", state: TimeState, } | { "type": "Delta", sequence: string, state: TimeState, } | { "type": "QueryResult", request: string, supported: boolean, reason_key: string | null, state: TimeState | null, } | { "type": "WorldResult", request: string, supported: boolean, reason_key: string | null, world: WorldView | null, } | { "type": "Notice", key: string, } | { "type": "MilitaryResult", request: string, supported: boolean, reason_key: string | null, military: MilitaryView | null, } | { "type": "MilitaryNormalLedgerCapabilityResult", request: string, supported: boolean, reason_key: string | null, } | { "type": "MilitaryNormalLedgerResult", request: string, supported: boolean, reason_key: string | null, ledger: MilitaryNormalLedgerView | null, } | { "type": "ProductionResult", request: string, supported: boolean, reason_key: string | null, production: ProductionView | null, } | { "type": "EconomyResult", request: string, supported: boolean, reason_key: string | null, economy: EconomyView | null, };
export type EconomyCommand = { "type": "Allocate", ratios_bits: [string, string, string, string], } | { "type": "Construct", project: string, state: number, building: string, } | { "type": "Cancel", project: string, } | { "type": "Reorder", projects: Array<string>, } | { "type": "ChangeLaw", law: string, };
export type FixedValue = { value: string, bits: string, fractional_bits: number, };
export type LawSelection = { category: string, law: string, name_key: string, };
export type EconomyResource = { resource: string, value: string, };
export type EconomyStateFlow = { state: number, population: string, resources: Array<EconomyResource>, };
export type IndustryContribution = { state: number, building: string, levels: string, unit_ic: FixedValue, value: FixedValue, };
export type IndustryMultiplier = { source: string, factor: FixedValue, applied: FixedValue, };
export type EconomyLedgerView = { tick: string, laws: Array<LawSelection>, stability: FixedValue, capacity: string, contributions: Array<IndustryContribution>, state_flows: Array<EconomyStateFlow>, population: string, resources: Array<EconomyResource>, multipliers: Array<IndustryMultiplier>, total_ic: FixedValue, minimum: FixedValue, ratios: [FixedValue, FixedValue, FixedValue, FixedValue], allocation: [FixedValue, FixedValue, FixedValue, FixedValue], consumer_residual: FixedValue, };
export type ConstructionProjectView = { id: string, state: number, building: string, target: string, progress: FixedValue, dormancy: string | null, };
export type ConstructionEntryView = { state: number, building: string, target: string, starting_progress: FixedValue, cost: FixedValue, daily_cap: FixedValue, infrastructure: FixedValue, owner: number, factor_evaluated: boolean, project: string, factor: FixedValue, consumed: FixedValue, applied: FixedValue, discarded: FixedValue, completed: boolean, dormancy: string | null, };
export type ConstructionLedgerView = { tick: string, budget: FixedValue, entries: Array<ConstructionEntryView>, unused: FixedValue, };
export type EconomyNationView = { nation: number, laws: Array<LawSelection>, political_capital: FixedValue, stability: FixedValue, mobilization: FixedValue, ratios: [FixedValue, FixedValue, FixedValue, FixedValue], committed: string, reserved: string, capacity: string, available: string, overcommitted: string, projects: Array<ConstructionProjectView>, ledger: EconomyLedgerView, construction: ConstructionLedgerView, };
export type EconomyView = { state_hash: string, pending: Array<EconomyPendingView>, definitions_hash: string, nations: Array<EconomyNationView>, industrial_scores: Array<IndustrialScoreView> | null, };
export type IndustrialScoreView = { nation: number, tick: string, input_tick: string, weight: FixedValue, input: FixedValue, term: FixedValue, };
export type AuthorityCommandView = { "type": "Pause", paused: boolean, } | { "type": "SetSpeed", speed: number, } | { "type": "Move", unit: number, destination: number, } | { "type": "Stop", unit: number, } | { "type": "Effects", program: string, } | { "type": "Economy", command: EconomyCommand, } | { "type": "Production", command: ProductionCommand, } | { "type": "Military", command: MilitaryCommand, };
export type EconomyPendingView = { tick: string, nation: number, sequence: string, command: AuthorityCommandView, };
export type ProductionCommand = { "type": "Create", model: string, requested_ic_bits: string, } | { "type": "SetIC", line: string, requested_ic_bits: string, } | { "type": "Pause", line: string, paused: boolean, } | { "type": "Switch", line: string, model: string, } | { "type": "Cancel", line: string, };
export type ProductionModelView = { model: string, name_key: string, family: string, generation: number, unit_cost: FixedValue, resources: Array<ProductionModelResourceView>, };
export type ProductionModelResourceView = { resource: string, per_item: FixedValue, };
export type ProductionStockView = { model: string, available: string, };
export type ProductionNationView = { nation: number, allowed_models: Array<string>, stock: Array<ProductionStockView>, military_ic: FixedValue, };
export type ProductionLineView = { id: string, nation: number, model: string, requested_ic: FixedValue, paused: boolean, efficiency: FixedValue, carry: FixedValue, };
export type ProductionResourceView = { resource: string, required: FixedValue, reserved: FixedValue, debited: FixedValue, };
export type ProductionLineDayView = { starting: ProductionLineView, effective_ic: FixedValue, stability_factor: FixedValue, planned: FixedValue, fulfillment: FixedValue, actual: FixedValue, output: string, ending_efficiency: FixedValue, ending_carry: FixedValue, resources: Array<ProductionResourceView>, };
export type ProductionFlowView = { resource: string, flow: string, required_raw: string, reserved_raw: string, debited_raw: string, unused_raw: string, };
export type ProductionNationDayView = { nation: number, budget: FixedValue, stability: FixedValue, unused_ic: FixedValue, flows: Array<ProductionFlowView>, lines: Array<ProductionLineDayView>, };
export type ProductionDayView = { tick: string, nations: Array<ProductionNationDayView>, };
export type ProductionDiscardView = { tick: string, line: string, nation: number, model: string, carry: FixedValue, };
export type ProductionPendingView = { tick: string, nation: number, sequence: string, command: ProductionCommand, };
export type ProductionView = { state_hash: string, definitions_hash: string, next_line_id: string, models: Array<ProductionModelView>, nations: Array<ProductionNationView>, lines: Array<ProductionLineView>, day: ProductionDayView | null, discards: Array<ProductionDiscardView>, pending: Array<ProductionPendingView>, };
export type MilitaryCommand = { "type": "Train", template: string, } | { "type": "Cancel", job: string, } | { "type": "Deploy", job: string, army: string, province: number, allow_understrength: boolean, } | { "type": "SetPriority", army: string, priority: number, };
export type MilitaryEquipmentView = { model: string, count: string, };
export type MilitaryRemainderView = { field: string, numerator_remainder: string, };
export type MilitaryNormalView = { manpower: string, equipment: Array<MilitaryEquipmentView>, strength: FixedValue, soft_fire: FixedValue, hard_fire: FixedValue, defense: FixedValue, breakthrough: FixedValue, frontage: FixedValue, supply_use: FixedValue, organization: FixedValue, armor: FixedValue, piercing: FixedValue, speed_kmh: FixedValue, weighted_remainders: Array<MilitaryRemainderView>, };
export type MilitaryArmyView = { id: string, nation: number, general: string, division_limit: number, priority: number, divisions: Array<string>, };
export type MilitaryDivisionView = { id: string, nation: number, army: string, province: number, template: string, normal: MilitaryNormalView, manpower: string, equipment: Array<MilitaryEquipmentView>, };
export type MilitaryJobStatus = "Pending" | "Training" | "Ready" | "Cancelled" | "Deployed";
export type MilitaryJobView = { id: string, nation: number, template: string, normal: MilitaryNormalView, training_days: number, status: MilitaryJobStatus, progress_days: number, start_tick: string | null, reserved_manpower: string, equipment: Array<MilitaryEquipmentView>, division: string | null, };
export type MilitaryBackgroundView = { nation: number, committed: string, reserved: string, };
export type MilitaryTemplateView = { template: string, training_days: number, normal: MilitaryNormalView, };
export type MilitaryPendingView = { tick: string, nation: number, sequence: string, command: MilitaryCommand, };
export type MilitaryView = { state_hash: string, definitions_hash: string, next_job_id: string, next_division_id: string, templates: Array<MilitaryTemplateView>, armies: Array<MilitaryArmyView>, divisions: Array<MilitaryDivisionView>, jobs: Array<MilitaryJobView>, background: Array<MilitaryBackgroundView>, pending: Array<MilitaryPendingView>, };
export type MilitaryNormalLedgerEntry = { id: string, role: string, position: number, component: string, value: FixedValue, accumulated: FixedValue, };
export type MilitaryNormalLedgerField = { field: string, base: FixedValue, value: FixedValue, entries: Array<MilitaryNormalLedgerEntry>, };
export type MilitaryNormalLedgerView = { definitions_hash: string, state_hash: string, tick: string, template: string, fields: Array<MilitaryNormalLedgerField>, };
