[package]
name = "oh_sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
oh_data.workspace = true
oh_core.workspace = true
serde = { version = "=1.0.229", features = ["derive"] }

[dev-dependencies]
proptest = { version = "=1.11.0", default-features = false, features = ["std"] }
