import pathlib,shutil,subprocess,json,sys
sys.stdout.reconfigure(encoding='utf8')
R=pathlib.Path(r'E:/openhoi/.orchestrator/wt/WP-09-verify');O=R/'target/wp09-verify'
n='scenarios/m1/nations/NTH.toml';s='scenarios/m1/scenario.toml';m='maps/testland/states.toml';v='maps/testland/visuals.toml'
cases=[('duplicate-tags',s,'["NTH", "STH"]','["NTH", "NTH"]'),('empty-nations',s,'["NTH", "STH"]','[]'),('missing-nation',s,'["NTH", "STH"]','["NTH", "MISSING"]'),('lower-tag',s,'["NTH", "STH"]','["nth", "STH"]'),('traversal-tag',s,'["NTH", "STH"]','["../NTH", "STH"]'),('id-overflow',n,'id = 1','id = 65536'),('negative-id',n,'id = 1','id = -1'),('empty-name',n,'name_key = "nation-testland-north"','name_key = ""'),('empty-government',n,'government_key = "government-test-republic"','government_key = ""'),('missing-color',n,'color = [40, 100, 180]\n',''),('negative-color',n,'[40, 100, 180]','[-1, 100, 180]'),('color-overflow',n,'[40, 100, 180]','[40, 256, 180]'),('short-color',n,'[40, 100, 180]','[40, 100]'),('capital-lake',n,'capital = 10','capital = 60'),('capital-missing',n,'capital = 10','capital = 65535'),('ideology-sum',n,'"0.75"','"0.5"'),('ideology-negative',n,'"0.75"','"-0.75"'),('ideology-overflow',n,'"0.75"','"9999999999999999999999999999999999"'),('ideology-empty',n,'[ideology_support]\nideology-test-civic = "0.75"\nideology-test-local = "0.25"','[ideology_support]'),('duplicate-id','scenarios/m1/nations/STH.toml','id = 2','id = 1'),('missing-owner',s,'1 = "NTH"\n',''),('unknown-owner',s,'1 = "NTH"','1 = "NOPE"'),('unknown-state',s,'1 = "NTH"','65535 = "NTH"'),('unknown-control',s,'20 = "STH"','20 = "NOPE"'),('sea-control',s,'20 = "STH"','50 = "STH"'),('unknown-column',n,'government_key =','unrecognized_column ='),('duplicate-column',n,'id = 1','id = 1\nid = 2'),('infra-overflow',m,'infrastructure = 1','infrastructure = 2147483648'),('missing-palette',v,'1 = [140, 95, 170]\n','')]
rows=[]
for name,file,a,b in cases:
 dst=O/'fixtures'/name;shutil.copytree(R/'data/packs/testland',dst,dirs_exist_ok=True);p=dst/file;t=p.read_text();assert a in t,(name,a);p.write_text(t.replace(a,b));res=subprocess.run([str(R/'target/debug/wp09-independent-probe.exe'),str(dst),'validate'],cwd=R,capture_output=True,text=True,encoding='utf8',errors='replace');row={'name':name,'exit':res.returncode,'output':res.stdout+res.stderr,'expected':'reject'};rows.append(row);print(json.dumps(row,ensure_ascii=False))
(O/'data-probes.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf8');assert all(r['exit'] in [1,2] for r in rows)
