use oh_core::{NationId,canonical_bytes};
use oh_sim::{Simulation,Command,save_state::*};
use oh_save::{SaveContext,Limits,decode,encode,HeaderV1};
use std::{fs,path::Path,io::Write};
const Q:i64=1<<32;
fn hex(b:&[u8])->String {b.iter().map(|x|format!("{x:02x}")).collect()}
fn row(source:Option<&str>,op:LedgerOpV1,value:i64,accumulated:i64)->EntryV1{EntryV1{source:source.map(str::to_owned),op,value,accumulated}}
fn initial(c:&SaveContext)->Simulation{
 let mut d=c.simulation(0x123456789abcdef0).unwrap().export_save().unwrap();
 d.config=TimeV1{speed_ms_per_tick:[0,19,13,7,3],initial_speed:2};d.state.speed=4;
 let w=d.world.as_mut().unwrap();
 w.inputs.nations[0].government="government-independent".into();
 w.inputs.nations[0].support=vec![("independent.a".into(),Q-1),("independent.z".into(),1)];
 let s=&mut w.inputs.states[0];s.population=3456;s.resources=vec![("steel".into(),71)];s.buildings=vec![("industry".into(),9)];s.base=2*Q+1;
 s.modifiers=vec![ModifierV1{source:"fresh.add".into(),target_stat:"infrastructure".into(),op:ModifierOpV1::Add,value:Q,expires:Some(29)},ModifierV1{source:"fresh.expired".into(),target_stat:"infrastructure".into(),op:ModifierOpV1::Add,value:-1,expires:Some(0)},ModifierV1{source:"fresh.mul".into(),target_stat:"infrastructure".into(),op:ModifierOpV1::Mul,value:3*Q/2,expires:None}];
 s.infrastructure=19327352833;s.ledger=LedgerV1{target_stat:"infrastructure".into(),tick:0,value:s.infrastructure,entries:vec![row(None,LedgerOpV1::Base,2*Q+1,2*Q+1),row(Some("fresh.add"),LedgerOpV1::Add,Q,3*Q+1),row(Some("fresh.mul"),LedgerOpV1::Mul,3*Q/2,19327352833)]};
 let mut sim=Simulation::from_save(d,c.restore_context()).unwrap();
 for(t,n,seq,cmd) in [(28,65535,1,Command::SetSpeed(5)),(28,42,2,Command::Pause(false)),(28,0,9,Command::SetSpeed(2)),(30,0,4,Command::SetSpeed(3)),(60,0,5,Command::SetSpeed(1))]{sim.enqueue(t,NationId(n),seq,cmd).unwrap();}sim
}
fn emit(sim:&Simulation)->serde_json::Value {serde_json::json!({"dto":sim.export_save().unwrap(),"canonical_hex":hex(&canonical_bytes(sim).unwrap()),"hash":format!("{:016x}",sim.state_hash().unwrap())})}
fn advance(s:&mut Simulation,n:u64){for _ in 0..n{assert!(s.step().unwrap().advanced)}}
fn capture(pack:&Path,out:&Path){fs::create_dir_all(out).unwrap();let c=SaveContext::national(pack,"m1").unwrap();let mut s=initial(&c);let begin=emit(&s);advance(&mut s,28);let split=emit(&s);let bytes=encode(&s,&c,0,vec![0,65535]).unwrap();oh_save::write_atomic(&out.join("saved.ohsave"),&bytes,&c).unwrap();let h=oh_save::inspect_header(&bytes,&Limits::default()).unwrap();assert_eq!(h.saved_at_utc,0);
 let mut paused=s.clone();paused.enqueue(28,NationId(65535),10,Command::Pause(true)).unwrap();assert!(!paused.step().unwrap().advanced);let pb=encode(&paused,&c,0,vec![]).unwrap();oh_save::write_atomic(&out.join("paused.ohsave"),&pb,&c).unwrap();assert_eq!(paused.pending_commands().len(),2);let paused_report=emit(&paused);paused.enqueue(28,NationId(0),11,Command::Pause(false)).unwrap();assert!(paused.step().unwrap().advanced);
 let step=s.step().unwrap();assert_eq!(step.commands.iter().map(|x|(x.nation.0,x.sequence)).collect::<Vec<_>>(),[(0,9),(42,2),(65535,1)]);assert_eq!(s.snapshot().speed(),5);let expiry=emit(&s);advance(&mut s,1);let after=emit(&s);advance(&mut s,31);let continuous=emit(&s);
 fs::write(out.join("capture.json"),serde_json::to_vec_pretty(&serde_json::json!({"pid":std::process::id(),"header":h,"pack":c.pack(),"begin":begin,"split":split,"paused":paused_report,"expiry":expiry,"after":after,"continuous":continuous})).unwrap()).unwrap();println!("{}",serde_json::json!({"pid":std::process::id(),"split":split["hash"],"resumed":continuous["hash"]}));
}
fn resume(pack:&Path,file:&Path,out:&Path){let c=SaveContext::national(pack,"m1").unwrap();let mut s=decode(&fs::read(file).unwrap(),&c,false).unwrap().simulation;let initial=emit(&s);advance(&mut s,33);let final_report=emit(&s);fs::write(out,serde_json::to_vec_pretty(&serde_json::json!({"pid":std::process::id(),"initial":initial,"final":final_report})).unwrap()).unwrap();println!("{}",serde_json::json!({"pid":std::process::id(),"initial":initial["hash"],"final":final_report["hash"]}));}
fn head_bytes(b:&[u8],h:&HeaderV1)->Vec<u8>{let e=10+u32::from_le_bytes(b[6..10].try_into().unwrap()) as usize;let hb=canonical_bytes(h).unwrap();let mut r=b[..6].to_vec();r.extend((hb.len() as u32).to_le_bytes());r.extend(hb);r.extend(&b[e..]);r}
fn body_bytes(b:&[u8],d:&SimulationSaveV1)->Vec<u8>{let e=10+u32::from_le_bytes(b[6..10].try_into().unwrap()) as usize;let mut r=b[..e].to_vec();r.extend(zstd::stream::encode_all(canonical_bytes(d).unwrap().as_slice(),3).unwrap());r}
fn checks(pack:&Path,out:&Path){let c=SaveContext::national(pack,"m1").unwrap();let mut s=initial(&c);advance(&mut s,28);let orig=s.export_save().unwrap();let before=canonical_bytes(&s).unwrap();let hash=s.state_hash().unwrap();let queue=s.pending_commands().clone();let bytes=encode(&s,&c,0,vec![0,65535]).unwrap();let mut records=vec![];
 let mutations:Vec<(&str,Box<dyn Fn(&mut SimulationSaveV1)>)>=vec![
 ("year0",Box::new(|d|d.state.date.year=0)),("month13",Box::new(|d|d.state.date.month=13)),("day0",Box::new(|d|d.state.date.day=0)),("nonleap",Box::new(|d|d.state.date=DateV1{year:1900,month:2,day:29})),("hour24",Box::new(|d|d.state.hour=24)),("tickdate",Box::new(|d|d.state.tick+=1)),("speed0",Box::new(|d|d.state.speed=0)),("speed6",Box::new(|d|d.state.speed=6)),("config0",Box::new(|d|d.config.initial_speed=0)),("config6",Box::new(|d|d.config.initial_speed=6)),("queuepast",Box::new(|d|d.queue[0].tick=27)),("queuedupe",Box::new(|d|d.queue.insert(0,d.queue[0].clone()))),("queueorder",Box::new(|d|d.queue.reverse())),("queueinvalid",Box::new(|d|d.queue[0].command=CommandV1::SetSpeed(6))),("worldnone",Box::new(|d|d.world=None)),("defs",Box::new(|d|d.world.as_mut().unwrap().definitions_hash^=1)),
 ("nationduplicate",Box::new(|d|{let x=&mut d.world.as_mut().unwrap().inputs.nations;x[1].id=x[0].id;})),("nationmissing",Box::new(|d|{d.world.as_mut().unwrap().inputs.nations.pop();})),("nationunknown",Box::new(|d|d.world.as_mut().unwrap().inputs.nations[0].id=17)),("tag",Box::new(|d|d.world.as_mut().unwrap().inputs.nations[0].tag="FAKE".into())),("governmentempty",Box::new(|d|d.world.as_mut().unwrap().inputs.nations[0].government.clear())),("supportsum",Box::new(|d|d.world.as_mut().unwrap().inputs.nations[0].support[0].1+=1)),("supportneg",Box::new(|d|d.world.as_mut().unwrap().inputs.nations[0].support[0].1=-1)),("supportdupe",Box::new(|d|{let x=&mut d.world.as_mut().unwrap().inputs.nations[0].support;x.push(x[0].clone());})),
 ("stateunknown",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].id=18)),("ownerunknown",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].owner=18)),("populationneg",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].population=-1)),("resourceref",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].resources[0].0="fake".into())),("resourceneg",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].resources[0].1=-1)),("buildingref",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].buildings[0].0="fake".into())),("buildingneg",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].buildings[0].1=-1)),("resourcedupe",Box::new(|d|{let x=&mut d.world.as_mut().unwrap().inputs.states[0].resources;x.push(x[0].clone());})),
 ("basebit",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].base+=1)),("baseneg",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].base=-1)),("modifierdupe",Box::new(|d|{let x=&mut d.world.as_mut().unwrap().inputs.states[0].modifiers;x.insert(0,x[0].clone());})),("modifieroverflow",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].modifiers[0].value=i64::MAX)),("modifiersource",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].modifiers[0].source.clear())),("modifiertarget",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].modifiers[0].target_stat="fake".into())),("modifierorder",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].modifiers.reverse())),("expirybit",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].modifiers[0].expires=Some(28))),
 ("appliedbit",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].infrastructure^=1)),("ledgertick",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.tick+=1)),("ledgertarget",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.target_stat="fake".into())),("ledgervalue",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.value^=1)),("entrysource",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.entries[0].source=Some("fake".into()))),("entryop",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.entries[0].op=LedgerOpV1::Add)),("entryvalue",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.entries[0].value^=1)),("entryaccum",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.entries[0].accumulated^=1)),("entryorder",Box::new(|d|d.world.as_mut().unwrap().inputs.states[0].ledger.entries.reverse())),
 ("provinceunknown",Box::new(|d|d.world.as_mut().unwrap().inputs.provinces[0].id=19)),("provincestate",Box::new(|d|d.world.as_mut().unwrap().inputs.provinces[0].state=Some(901))),("landnull",Box::new(|d|d.world.as_mut().unwrap().inputs.provinces[0].owner=None)),("waterowner",Box::new(|d|d.world.as_mut().unwrap().inputs.provinces.iter_mut().find(|p|p.state.is_none()).unwrap().owner=Some(0))),("controllerref",Box::new(|d|d.world.as_mut().unwrap().inputs.provinces[0].controller=Some(19)))];
 for(name,change) in mutations{let mut d=orig.clone();change(&mut d);let err=Simulation::from_save(d.clone(),c.restore_context()).err().expect(name);for force in [false,true]{assert!(decode(&body_bytes(&bytes,&d),&c,force).is_err(),"{name}");}assert_eq!(canonical_bytes(&s).unwrap(),before);assert_eq!(s.state_hash().unwrap(),hash);assert_eq!(s.pending_commands(),&queue);records.push(serde_json::json!({"dto":name,"error":err,"force_rejected":true}));}
 for speed in 1..=5{let mut d=orig.clone();d.state.speed=speed;let x=Simulation::from_save(d,c.restore_context()).unwrap();let restored=decode(&encode(&x,&c,0,vec![]).unwrap(),&c,false).unwrap().simulation;assert_eq!(restored.export_save().unwrap(),x.export_save().unwrap());}
 for badspeed in [0,6]{let mut invalid=s.clone();invalid.enqueue(28,NationId(1),0,Command::SetSpeed(badspeed)).unwrap();let b=canonical_bytes(&invalid).unwrap();assert!(encode(&invalid,&c,0,vec![]).is_err());assert_eq!(canonical_bytes(&invalid).unwrap(),b);assert!(invalid.step().unwrap().commands.iter().any(|x|x.result.is_err()));}
 let h=oh_save::inspect_header(&bytes,&Limits::default()).unwrap();let changes:Vec<(&str,Box<dyn Fn(&mut HeaderV1)>)>=vec![("engine",Box::new(|h|h.engine_version="0.2.0".into())),("format",Box::new(|h|h.format_version=2)),("scenario",Box::new(|h|h.scenario_id="bad".into())),("packid",Box::new(|h|h.packs[0].id="bad".into())),("packempty",Box::new(|h|h.packs.clear())),("packdupe",Box::new(|h|h.packs.push(h.packs[0].clone()))),("date",Box::new(|h|h.game_date.day+=1)),("tick",Box::new(|h|h.tick+=1)),("seed",Box::new(|h|h.seed^=1)),("hash",Box::new(|h|h.state_hash^=1)),("playersdupe",Box::new(|h|h.player_nations.push(65535))),("playerunknown",Box::new(|h|h.player_nations=vec![19])),("timeneg",Box::new(|h|h.saved_at_utc=-1)),("timemax",Box::new(|h|h.saved_at_utc=253402300800)),("defs",Box::new(|h|h.definitions_hash=Some(0))),("defines",Box::new(|h|h.effective_defines_hash^=1))];
 for(name,ch)in changes{let mut hh=h.clone();ch(&mut hh);for f in [false,true]{assert!(decode(&head_bytes(&bytes,&hh),&c,f).is_err(),"header {name}");}records.push(serde_json::json!({"header":name,"force_rejected":true}));}
 for field in [0,1]{let mut hh=h.clone();if field==0{hh.packs[0].content_hash^=1}else{hh.packs[0].version="0.2.0".into()}let b=head_bytes(&bytes,&hh);assert!(decode(&b,&c,false).is_err());let loaded=decode(&b,&c,true).unwrap();assert_eq!(loaded.warnings.len(),1);assert_eq!(loaded.simulation.state_hash().unwrap(),hash);}
 let later=encode(&s,&c,253402300799,vec![0,65535]).unwrap();assert_ne!(bytes,later);assert_eq!(decode(&later,&c,false).unwrap().simulation.state_hash().unwrap(),hash);
 let mut count=0;for n in 0..bytes.len(){for f in [false,true]{assert!(decode(&bytes[..n],&c,f).is_err(),"trunc {n}");count+=1;}}
 for v in [0u16,2,65535]{let mut b=bytes.clone();b[4..6].copy_from_slice(&v.to_le_bytes());assert!(decode(&b,&c,true).is_err());count+=1;}
 for n in [0u32,u32::MAX]{let mut b=bytes.clone();b[6..10].copy_from_slice(&n.to_le_bytes());assert!(decode(&b,&c,true).is_err());count+=1;}
 let e=10+u32::from_le_bytes(bytes[6..10].try_into().unwrap()) as usize;
 for tail in [vec![0],bytes[e..].to_vec(),zstd::stream::encode_all(&[][..],3).unwrap()]{let mut b=bytes.clone();b.extend(tail);for f in [false,true]{assert!(decode(&b,&c,f).is_err());count+=1;}}
 let mut compression_equivalent=vec![];for i in e..bytes.len(){let mut b=bytes.clone();b[i]^=128;match decode(&b,&c,true){Err(_)=>{},Ok(loaded)=>{assert_eq!(loaded.simulation.export_save().unwrap(),orig,"compressed changed plaintext {i}");assert_eq!(loaded.simulation.state_hash().unwrap(),hash);assert_eq!(zstd::stream::decode_all(&b[e..]).unwrap(),zstd::stream::decode_all(&bytes[e..]).unwrap());compression_equivalent.push(i);}}count+=1;}
 let mut body=zstd::stream::decode_all(&bytes[e..]).unwrap();body.push(0);let mut b=bytes[..e].to_vec();b.extend(zstd::stream::encode_all(body.as_slice(),3).unwrap());assert!(decode(&b,&c,true).is_err());
 let mut enc=zstd::stream::write::Encoder::new(Vec::new(),3).unwrap();enc.window_log(24).unwrap();enc.write_all(&vec![0;9_000_000]).unwrap();let mut bomb=bytes[..e].to_vec();bomb.extend(enc.finish().unwrap());assert!(decode(&bomb,&c,true).is_err());
 for l in [Limits{body_max_bytes:8,..Limits::default()},Limits{allocation_budget_bytes:1,..Limits::default()},Limits{header_max_bytes:8,..Limits::default()},Limits{file_max_bytes:8,..Limits::default()},Limits{queue_max_entries:1,..Limits::default()}]{assert!(oh_save::decode_with_limits(&bytes,&c,true,&l).is_err());}
 let report=serde_json::json!({"records":records,"container_cases":count,"compression_metadata_equivalent_positions":compression_equivalent,"speeds":5,"display_time_hash_preserved":true,"live_queue_hash_preserved":true});fs::write(out,serde_json::to_vec_pretty(&report).unwrap()).unwrap();println!("dto/header={} container={count}",report["records"].as_array().unwrap().len());
}
fn main(){let a:Vec<_>=std::env::args().collect();match a[1].as_str(){"proto"=>fs::write(&a[2],oh_proto::typescript()).unwrap(),"capture"=>capture(Path::new(&a[2]),Path::new(&a[3])),"resume"=>resume(Path::new(&a[2]),Path::new(&a[3]),Path::new(&a[4])),"checks"=>checks(Path::new(&a[2]),Path::new(&a[3])),"decompress"=>{let b=fs::read(&a[2]).unwrap();let e=10+u32::from_le_bytes(b[6..10].try_into().unwrap()) as usize;fs::write(&a[3],zstd::stream::decode_all(&b[e..]).unwrap()).unwrap();},_=>panic!("mode")}}
