//! M0 MessagePack contract. Rust is the sole protocol type source.
use serde::{Deserialize, Serialize};
use ts_rs::TS;
pub const PROTOCOL_VERSION: &str = "m0-v1";
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "type")]
pub enum TimeCommand {
    Pause { paused: bool },
    SetSpeed { speed: u8 },
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "type")]
pub enum ClientMessage {
    Hello {
        protocol_version: String,
    },
    Create {
        scenario: String,
        seed: String,
        mode: String,
    },
    Join {
        session: String,
        nation: Option<String>,
    },
    Command {
        sequence: String,
        command: TimeCommand,
    },
    Query {
        request: String,
        kind: String,
    },
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct PackInfo {
    pub id: String,
    pub version: String,
    pub hash: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct TimeState {
    /// Fully formatted by the server; browsers never calculate dates.
    pub date: String,
    pub hour: u8,
    /// Decimal text preserves full u64 precision in JavaScript.
    pub tick: String,
    pub paused: bool,
    pub speed: u8,
}
impl From<&oh_sim::State> for TimeState {
    fn from(state: &oh_sim::State) -> Self {
        Self {
            date: state.date().to_string(),
            hour: state.hour(),
            tick: state.tick().to_string(),
            paused: state.paused(),
            speed: state.speed(),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "type")]
pub enum ServerMessage {
    Welcome {
        engine_version: String,
        protocol_version: String,
        accepted: bool,
        reason_key: Option<String>,
        packs: Vec<PackInfo>,
        sessions: Vec<String>,
    },
    CommandResult {
        sequence: String,
        accepted: bool,
        reason_key: Option<String>,
    },
    Snapshot {
        state: TimeState,
    },
    Delta {
        sequence: String,
        state: TimeState,
    },
    QueryResult {
        request: String,
        supported: bool,
        reason_key: Option<String>,
        state: Option<TimeState>,
    },
    Notice {
        key: String,
    },
}
pub fn encode<T: Serialize>(message: &T) -> Result<Vec<u8>, rmp_serde::encode::Error> {
    rmp_serde::to_vec_named(message)
}
pub fn decode_client(bytes: &[u8]) -> Result<ClientMessage, rmp_serde::decode::Error> {
    rmp_serde::from_slice(bytes)
}
pub fn decode_server(bytes: &[u8]) -> Result<ServerMessage, rmp_serde::decode::Error> {
    rmp_serde::from_slice(bytes)
}
pub fn typescript() -> String {
    let mut out = format!(
        "// Generated by oh_proto; do not edit.\nexport const PROTOCOL_VERSION = {PROTOCOL_VERSION:?} as const;\n"
    );
    for declaration in [
        TimeCommand::decl(&ts_rs::Config::default()),
        PackInfo::decl(&ts_rs::Config::default()),
        TimeState::decl(&ts_rs::Config::default()),
        ClientMessage::decl(&ts_rs::Config::default()),
        ServerMessage::decl(&ts_rs::Config::default()),
    ] {
        out.push_str("export ");
        for line in declaration.lines() {
            out.push_str(line.trim_end());
            out.push('\n');
        }
    }
    out
}
