from pathlib import Path
import json,hashlib
OUT=Path(__file__).resolve().parent;source=OUT/'current-probes/lifecycle.cjs';target=OUT/'current-probes/native-lifecycle.cjs';s=source.read_text(encoding='utf8')
s=s.replace('changed=false;','changed=false;let activeCDP=null;')
s=s.replace("await expect(map).toHaveAttribute('data-frames',/^[1-9]\\d*$/);const pos=await point(1,1)","await expect.poll(()=>map.locator('..').getByRole('status').count()).toBe(0);await expect.poll(async()=>Number(await map.getAttribute('data-frames'))).toBeGreaterThan(5);const pos=await point(1,1)")
s=s.replace("image=png(await map.screenshot({path:__dirname+`/life-${name}-${force}-${label}.png`})),rgb=image.pixel(pos.x*image.width/box.width,pos.y*image.height/box.height)","bytes=activeCDP?Buffer.from((await activeCDP.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'):await map.screenshot({path:__dirname+`/native-life-${name}-${force}-${label}.png`}),image=png(bytes),rgb=activeCDP?image.pixel((box.x+pos.x)*image.width/1280,(box.y+pos.y)*image.height/720):image.pixel(pos.x*image.width/box.width,pos.y*image.height/box.height)")
s=s.replace('const p=await probe();assert.equal(p.observers,1);',"if(activeCDP)fs.writeFileSync(__dirname+`/native-life-${name}-${force}-${label}.png`,bytes);const p=await probe();assert.equal(p.observers,1);")
start=s.index(" let dprFailure=false;if(");end=s.index("\n await expect(page.getByTestId('tick'))",start)
s=s[:start]+''' let dprFailure=false;if(['chrome','edge','chromium'].includes(name)){const cdp=await context.newCDPSession(page);activeCDP=cdp;for(const [step,dpr] of [2,1.5,1,2,1.5,1].entries()){const old=await map.locator('canvas').elementHandle(),before=await probe();await cdp.send('Emulation.setDeviceMetricsOverride',{width:1280,height:720,deviceScaleFactor:dpr,mobile:false});await expect.poll(async()=>(await probe()).dpr).toBe(dpr);await expect.poll(()=>map.locator('canvas').evaluate(c=>({x:c.width-Math.floor(c.clientWidth*devicePixelRatio),y:c.height-Math.floor(c.clientHeight*devicePixelRatio)}))).toEqual({x:0,y:0});await capture('dpr'+dpr+'-'+step);assert.equal((await probe()).dpr,dpr);assert.deepEqual(await cam(),saved);const after=await probe();if(backend==='webgl2'){assert.equal(after.contexts.length,before.contexts.length+1);assert.equal(await old.evaluate(c=>c.isConnected),false);assert.equal(await old.evaluate(c=>c.getContext('webgl2').isContextLost()),true);}else{assert.equal(await old.evaluate(c=>c.isConnected),true);assert.equal(after.devices,before.devices);}}await cdp.detach();activeCDP=null;}
 else steps.push({label:'dynamic-DPR',scope:'CDP unavailable; original viewport lifecycle only; nativeDPR2 in full205 config'});'''+s[end:]
s=s.replace("'/lifecycle-results.json'","'/native-lifecycle-results.json'");target.write_text(s,encoding='utf8')
(OUT/'native-lifecycle-fixture.json').write_text(json.dumps({'source':str(source),'sourceSHA256':hashlib.sha256(source.read_bytes()).hexdigest(),'executed':str(target),'executedSHA256':hashlib.sha256(target.read_bytes()).hexdigest(),'scope':'Separate supplemental fixture, original untouched. Native no-clip screenshot during liveCDP removes observed locator DPR restoration; six DPR changes exact buffer floor, same camera and real canvas/device lifecycle; original viewport/reset/404/cleanup assertions retained.'},indent=2));print(target)
