[package]
name = "oh_cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
oh_ai.workspace = true
oh_save.workspace = true
oh_sim.workspace = true
oh_data.workspace = true
oh_core.workspace = true
oh_proto.workspace = true
serde_json = "=1.0.151"
serde = { version = "=1.0.229", features = ["derive"] }
toml = "=1.1.6"
