import {test as base,expect,type Page} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
import {createServer} from 'node:net';
import {cpSync,mkdirSync,mkdtempSync,readFileSync,writeFileSync,createWriteStream,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {decode} from '@msgpack/msgpack';
import type {ClientMessage,ServerMessage} from '../src/proto/protocol';
type Hosts={fresh:string;restored:string;expected:{tick:string;paused_hash:string}};
async function freePort(){const server=createServer();await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));const address=server.address();if(!address||typeof address==='string')throw Error('port');const port=address.port;await new Promise<void>(done=>server.close(()=>done()));return port;}
const test=base.extend<{}, {hosts:Hosts}>({hosts:[async({},use,info)=>{
  const fixture=resolve(process.env.OH_M2_MILITARY_OUTPUT_DIR??'../target/wp23/checkpoint');
  const expected=JSON.parse(readFileSync(resolve(fixture,'expected.json'),'utf8')) as Hosts['expected'];
  const binary=resolve(process.env.OH_SERVER_EXECUTABLE??'../target/debug/oh_server');
  const output=resolve(info.project.outputDir,`m2-military-hosts-${info.workerIndex}`);mkdirSync(output,{recursive:true});
  const root=mkdtempSync(resolve(tmpdir(),'openhoi-wp23-browser-'));cpSync(resolve('../data/packs/testland_m2_military'),resolve(root,'testland'),{recursive:true});
  const children:ChildProcess[]=[],records:Array<{pid:number|undefined;args:string[];exitCode:number|null;signal:NodeJS.Signals|null;alive:boolean}>=[];
  const ledger=()=>writeFileSync(resolve(output,'pid-ledger.json'),JSON.stringify({owner:process.pid,records},null,2));
  const start=async(save?:string)=>{const port=await freePort(),args=['--port',String(port),'--pack-root',root,'--scenario','m2_military',...(save?['--load-save',save]:[])];const child=spawn(binary,args,{cwd:resolve('..'),stdio:['ignore','pipe','pipe']});children.push(child);const row={pid:child.pid,args,exitCode:null as number|null,signal:null as NodeJS.Signals|null,alive:true};records.push(row);ledger();child.stdout!.pipe(createWriteStream(resolve(output,`server-${port}.stdout`)));child.stderr!.pipe(createWriteStream(resolve(output,`server-${port}.stderr`)));child.on('exit',(code,signal)=>{row.exitCode=code;row.signal=signal;row.alive=false;ledger();});const url=`http://127.0.0.1:${port}`;await expect.poll(async()=>{if(child.exitCode!==null)throw Error('host exited');try{return(await fetch(url)).status;}catch{return 0;}}).toBe(200);return url;};
  try{const fresh=await start(),restored=await start(resolve(fixture,'paused-training.ohsave'));await use({fresh,restored,expected});}
  finally{for(const child of children){if(child.exitCode!==null||child.signalCode!==null)continue;const exited=new Promise<void>(done=>child.once('exit',()=>done()));child.kill('SIGINT');const timer=setTimeout(()=>child.kill('SIGKILL'),5000);try{await exited;}finally{clearTimeout(timer);}}for(const row of records){if(row.pid){try{process.kill(row.pid,0);row.alive=true;}catch{row.alive=false;}}expect(row.alive).toBe(false);expect(row.exitCode).toBe(0);}ledger();rmSync(root,{recursive:true});}
},{scope:'worker'}]});
function observe(page:Page){const sent:ClientMessage[]=[],received:ServerMessage[]=[];page.on('websocket',socket=>{socket.on('framesent',event=>{if(event.payload instanceof Buffer)sent.push(decode(event.payload) as ClientMessage);});socket.on('framereceived',event=>{if(event.payload instanceof Buffer)received.push(decode(event.payload) as ServerMessage);});});return{sent,received,queries:()=>sent.filter(m=>m.type==='Query'&&m.kind==='military'),deltas:()=>received.filter(m=>m.type==='Delta').length,replies:()=>received.filter((m):m is Extract<ServerMessage,{type:'MilitaryResult'}>=>m.type==='MilitaryResult')};}
for(const restored of [false,true])for(let n=1;n<=6;n++)test(`native ${restored?'restored Training':'fresh empty'} pack via existing Join N${String(n).padStart(2,'0')}`,async({page,hosts,request},info)=>{
  const wire=observe(page),url=restored?hosts.restored:hosts.fresh;await page.goto(url);const production=page.getByTestId('production-panel');await expect(production).toBeVisible();expect(wire.queries()).toHaveLength(0);
  await production.getByRole('combobox',{name:'Nation',exact:true}).selectOption(String(n));await production.getByRole('button',{name:'Start as selected nation',exact:true}).click();
  await expect.poll(()=>wire.sent.filter(m=>m.type==='Join').length).toBe(2);expect(wire.sent.filter(m=>m.type==='Join').at(-1)).toEqual({type:'Join',session:'local',nation:`N${String(n).padStart(2,'0')}`});
  await page.getByRole('button',{name:'Open military information',exact:true}).click();const panel=page.getByTestId('military-panel');await expect(panel).toHaveAttribute('data-status','ready');await expect(panel.locator('[data-military-template]')).toHaveCount(1);await expect(panel.locator('[data-military-template]')).toContainText('m2_small');await expect(panel.locator('[data-military-army]')).toHaveCount(6);await expect(panel.locator('[data-military-division]')).toHaveCount(0);
  const reply=wire.replies().filter(m=>m.supported).at(-1)!.military!;expect(reply.templates[0].normal.manpower).toBe('8');expect(reply.templates[0].normal.equipment).toEqual([{model:'m2_equipment_1',count:'6'}]);expect(reply.templates[0].training_days).toBe(2);expect(reply.armies.map(a=>a.divisions)).toEqual([[],[],[],[],[],[]]);
  if(restored){expect(reply.state_hash).toBe(hosts.expected.paused_hash);await expect(panel.locator('[data-military-job]')).toHaveCount(6);for(const j of reply.jobs){expect(j.status).toBe('Training');expect(j.equipment).toEqual([{model:'m2_equipment_1',count:'6'}]);expect(j.reserved_manpower).toBe('8');await expect(panel.locator(`[data-military-job="${j.id}"]`)).toContainText('Training');}}else{expect(reply.jobs).toEqual([]);expect(reply.next_job_id).toBe('0');await expect(panel.locator('[data-military-job]')).toHaveCount(0);}
  const joins=wire.sent.filter(m=>m.type==='Join').length;await panel.getByRole('combobox').selectOption(String(n));await expect(panel.locator('[data-military-army]')).toHaveCount(1);if(restored)await expect(panel.locator('[data-military-job]')).toHaveCount(1);expect(wire.sent.filter(m=>m.type==='Join')).toHaveLength(joins);
  const html=await(await request.get(url)).text(),script=html.match(/<script[^>]*src="([^"]+)"/)![1];expect(await(await request.get(url+script)).body()).toEqual(readFileSync(resolve('dist',script.slice(1))));
  await panel.getByRole('button',{name:'Close military information',exact:true}).click();await expect(panel).toHaveCount(0);const count=wire.queries().length,delta=wire.deltas();await expect.poll(()=>wire.deltas()).toBeGreaterThan(delta);expect(wire.queries()).toHaveLength(count);expect(wire.sent.filter(m=>m.type==='MilitaryCommand')).toHaveLength(0);
  writeFileSync(info.outputPath('native-wire.json'),JSON.stringify({sent:wire.sent,received:wire.received},null,2));
});
test('native Training in Korean mobile and keyboard close has no commands or closed queries',async({page,hosts},info)=>{
  const wire=observe(page);await page.goto(hosts.restored);await expect(page.getByTestId('production-panel')).toBeVisible();expect(wire.queries()).toHaveLength(0);
  const toggle=page.getByRole('button',{name:'Open military information',exact:true});await toggle.focus();await page.keyboard.press('Enter');const panel=page.getByTestId('military-panel');await expect(panel).toHaveAttribute('data-status','ready');await page.getByRole('combobox',{name:'Language',exact:true}).selectOption('ko');await expect(panel).toContainText('군사 정보');await expect(panel.locator('[data-military-job]')).toHaveCount(6);
  await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();expect(await panel.evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath('m2-training-mobile-ko.png'),fullPage:true});await panel.getByRole('button',{name:'군사 정보 닫기',exact:true}).focus();await page.keyboard.press('Enter');await expect(panel).toHaveCount(0);await expect(page.getByRole('button',{name:'군사 정보 열기',exact:true})).toBeFocused();const count=wire.queries().length,delta=wire.deltas();await expect.poll(()=>wire.deltas()).toBeGreaterThan(delta);expect(wire.queries()).toHaveLength(count);expect(wire.sent.filter(m=>m.type==='MilitaryCommand')).toHaveLength(0);
});
